# Generated by Django 5.2.10 on 2026-01-18 18:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('form_factor', models.CharField(choices=[('ATX', 'ATX'), ('mATX', 'Micro-ATX'), ('ITX', 'Mini-ITX')], max_length=10, verbose_name='Форм-фактор')),
                ('max_gpu_length', models.PositiveIntegerField(verbose_name='Макс. длина GPU (мм)')),
                ('max_cpu_cooler_height', models.PositiveIntegerField(verbose_name='Макс. высота кулера (мм)')),
                ('avg_used_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Средняя цена б/у')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('socket', models.CharField(choices=[('AM4', 'AMD AM4'), ('AM5', 'AMD AM5'), ('LGA1151', 'Intel LGA1151 v2'), ('LGA1200', 'Intel LGA1200'), ('LGA1700', 'Intel LGA1700')], max_length=20, verbose_name='Сокет')),
                ('cores', models.PositiveIntegerField(verbose_name='Количество ядер')),
                ('threads', models.PositiveIntegerField(verbose_name='Количество потоков')),
                ('base_clock', models.FloatField(verbose_name='Базовая частота (GHz)')),
                ('boost_clock', models.FloatField(verbose_name='Турбо частота (GHz)')),
                ('tdp', models.PositiveIntegerField(verbose_name='TDP (Вт)')),
                ('has_integrated_gpu', models.BooleanField(default=False, verbose_name='Встроенная графика')),
                ('benchmark_score', models.PositiveIntegerField(verbose_name='Benchmark Score')),
                ('avg_used_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Средняя цена б/у')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессоры',
                'ordering': ['-benchmark_score'],
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('vram', models.PositiveIntegerField(verbose_name='Видеопамять (GB)')),
                ('memory_type', models.CharField(choices=[('GDDR5', 'GDDR5'), ('GDDR6', 'GDDR6'), ('GDDR6X', 'GDDR6X')], max_length=10, verbose_name='Тип памяти')),
                ('core_clock', models.PositiveIntegerField(verbose_name='Частота ядра (MHz)')),
                ('tdp', models.PositiveIntegerField(verbose_name='TDP (Вт)')),
                ('length', models.PositiveIntegerField(verbose_name='Длина (мм)')),
                ('benchmark_score', models.PositiveIntegerField(verbose_name='Benchmark Score')),
                ('avg_used_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Средняя цена б/у')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Видеокарта',
                'verbose_name_plural': 'Видеокарты',
                'ordering': ['-benchmark_score'],
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('socket', models.CharField(choices=[('AM4', 'AMD AM4'), ('AM5', 'AMD AM5'), ('LGA1151', 'Intel LGA1151 v2'), ('LGA1200', 'Intel LGA1200'), ('LGA1700', 'Intel LGA1700')], max_length=20, verbose_name='Сокет')),
                ('chipset', models.CharField(max_length=50, verbose_name='Чипсет')),
                ('form_factor', models.CharField(choices=[('ATX', 'ATX'), ('mATX', 'Micro-ATX'), ('ITX', 'Mini-ITX')], max_length=10, verbose_name='Форм-фактор')),
                ('memory_type', models.CharField(choices=[('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=10, verbose_name='Тип памяти')),
                ('memory_slots', models.PositiveIntegerField(verbose_name='Слотов памяти')),
                ('max_memory', models.PositiveIntegerField(verbose_name='Максимум RAM (GB)')),
                ('avg_used_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Средняя цена б/у')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Материнская плата',
                'verbose_name_plural': 'Материнские платы',
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('wattage', models.PositiveIntegerField(verbose_name='Мощность (Вт)')),
                ('efficiency', models.CharField(choices=[('80+', '80 Plus'), ('Bronze', '80+ Bronze'), ('Silver', '80+ Silver'), ('Gold', '80+ Gold'), ('Platinum', '80+ Platinum')], max_length=20, verbose_name='Сертификат')),
                ('is_modular', models.BooleanField(default=False, verbose_name='Модульный')),
                ('avg_used_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Средняя цена б/у')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Блок питания',
                'verbose_name_plural': 'Блоки питания',
                'ordering': ['-wattage'],
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('memory_type', models.CharField(choices=[('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=10, verbose_name='Тип памяти')),
                ('capacity', models.PositiveIntegerField(verbose_name='Объём (GB)')),
                ('modules', models.PositiveIntegerField(verbose_name='Количество модулей')),
                ('speed', models.PositiveIntegerField(verbose_name='Частота (MHz)')),
                ('avg_used_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Средняя цена б/у')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Оперативная память',
                'verbose_name_plural': 'Оперативная память',
                'ordering': ['-capacity', '-speed'],
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сборки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичная сборка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.case', verbose_name='Корпус')),
                ('cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.cpu', verbose_name='Процессор')),
                ('gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.gpu', verbose_name='Видеокарта')),
                ('motherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.motherboard', verbose_name='Материнская плата')),
                ('psu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.psu', verbose_name='Блок питания')),
                ('ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.ram', verbose_name='Оперативная память')),
            ],
            options={
                'verbose_name': 'Сборка',
                'verbose_name_plural': 'Сборки',
                'ordering': ['-created_at'],
            },
        ),
    ]
